//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean CycleUp
        {
            get
            {
                return SteamVR_Actions.default_CycleUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean CycleDown
        {
            get
            {
                return SteamVR_Actions.default_CycleDown;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Scrub
        {
            get
            {
                return SteamVR_Actions.default_Scrub;
            }
        }
        
        public virtual SteamVR_Action_Boolean LaserPointer
        {
            get
            {
                return SteamVR_Actions.default_LaserPointer;
            }
        }
        
        public virtual SteamVR_Action_Boolean Timeline
        {
            get
            {
                return SteamVR_Actions.default_Timeline;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
